# Generated by Django 2.1.15 on 2020-04-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200407_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.TextField()),
                ('Age', models.TextField()),
                ('Height', models.TextField()),
                ('BodyWeight', models.TextField()),
                ('GamesQualify', models.TextField()),
                ('BackSquat', models.TextField()),
                ('CleanAndJerk', models.TextField()),
                ('Snatch', models.TextField()),
                ('Deadlift', models.TextField()),
                ('FightGoneBad', models.TextField()),
                ('MaxPullUps', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Womens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.TextField()),
                ('Age', models.TextField()),
                ('Height', models.TextField()),
                ('BodyWeight', models.TextField()),
                ('GamesQualify', models.TextField()),
                ('BackSquat', models.TextField()),
                ('CleanAndJerk', models.TextField()),
                ('Snatch', models.TextField()),
                ('Deadlift', models.TextField()),
                ('FightGoneBad', models.TextField()),
                ('MaxPullUps', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Update',
        ),
    ]
